### ISSUE TITLE
Document POST request

### ISSUE THREAD

**Issue by oncletom** [ehlo-io/ehlo#9]
In order to have an idea of the message structure.

Using protocol-buffers could solve the data structure and expose some easy encode/decode feature.

**Comment by Nasga** [comment]
Why protocol-buffers and not a bson, avro or thrift ?
I don't see a real advantage to abandon json here.

**Comment by oncletom** [comment]
Just a matter of simplicity and its inclusion in the npm ecosystem (works client/server-side and has API consumers for Java and Python, to cite only a few).

```
message Email {
  required string from = 1;
  required string to = 2;
  required map<string, string> headers = 2;
}
```

Providing just the JSON is good enough. Protocol buffer is not only smaller in term of footprint but you define your content structure in a simple portable way.

I thought about it just for the sake of documentation, but *interactive* in a sense you can actually use it to consume and expose data.

**Comment by Nasga** [comment]
Sorry for the delay.

I just add some documentation (a tcpdump + gif) about the json format and the post request.
I plan to release an online demo in a ~~near~~ futur.

Do you have another ideas to improve the README ?

**Comment by oncletom** [comment]
So far it seems to be good! Like the MX configuration as well :-)
